on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - run: python -m pip install -U pip
    - run: python -m pip install -r requirements.txt pyinstaller
    - run: pyinstaller build.spec
    # Optionally verify that it works (provided that it does not need user interaction)
    #- run: ./dist/MastotronApp
    - run: python setup.py sdist
    
    - uses: actions/upload-artifact@v2
      with:
        path: dist/*